### ISSUE TITLE
Upgrade from 8.02->8.03 still issues with Bookmarks

### ISSUE THREAD

**Issue by jonmach** [owncloud/bookmarks#158]
I've recently upgraded to 8.03 in order to resolve ongoing bookmarks issues since upgrading to 8 from 7.

I managed to work around a number of them manually but I saw that someone suggested that this is now resolved. Unfortunately not for me.

I removed the old apps/bookmarks, downloaded the latest bookmarks-master (from apps.owncloud.com) 8.0 (0.4). I still have the same problem of not being able to filter by bookmark (I never got that working). I briefly see the field and then it disappears.

I can see existing bookmarks fine and I can add new bookmarks. This is no different to before.

I also now have a number of errors appearing. Some of these look familiar, so I'm confused as to why they are still there. Will I need to manually patch these as well? I thought these were already resolved.

Invalid argument supplied for foreach() at /mypath/lib/private/app.php#1233
preg_split() expects parameter 2 to be string, array given at /mypath/lib/private/app.php#1230
Invalid argument supplied for foreach() at /mypath/lib/private/app.php#1233
Invalid argument supplied for foreach() at /mypath/lib/private/app.php#1233
preg_split() expects parameter 2 to be string, array given at /mypath/lib/private/app.php#1230
Invalid argument supplied for foreach() at /mypath/lib/private/app.php#1233

Any ideas?

**Comment by srissel** [comment]
Hi jonmach,

were you able to solve this issue?
I just upgraded from ownCloud 7.0.4 to the latest owncloud 8.
Seemed to work fine, except for this two errors appearing in the log, each time I load the app manager.

Kind regards,
Sascha.

**Comment by jonmach** [comment]
I'm afraid the problem still remains and the code isn't that obvious to me.  I have also put a couple of product improvement requests in that are also still outstanding.  Ah well, I'm not going to criticise if I'm not writing as much of the code myself :)

**Comment by srissel** [comment]
Thanks for your answer.
Do you really think, the two errors in the log are related to the bookmarks app?

I do not use the bookmarks app, but also experience the errors. The appear when opening ownclouds build in app manager.

I opened an issue myself:
#578

**Comment by jonmach** [comment]
I'm not sure whether the errors are related, but it was information that I thought might be pertinent. At the moment, I'm just using ^F to find bookmarks via tag. It's a terrible user experience but I'm more focused on saving bookmarks than finding them at the moment.  In addition, the additional clicks required to save bookmarks is poorly thought out.  Hopefully that is also resolved in the next version.

**Comment by blizzz** [comment]
Errors quoted in https://github.com/owncloud/bookmarks/issues/158#issue-80611207 suggest the problem to be in core (but not necessarily). To you still have issues with 8.0.5?
